
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdebug
spec:
  selector:
    matchLabels:
      app: cdebug
  template:
    metadata:
      labels:
        app: cdebug
    spec:
      containers:
      - name: cdebug
        image: uhub.service.ucloud.cn/naturelr/cdebug:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cdebug
spec:
  selector:
    app: cdebug
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
